apiVersion: v1
kind: Service
metadata:
  name: flask-service
  namespace: blog-project
spec:
  type: NodePort
  selector:
    app: flask-api
  ports:
    - port: 80
      targetPort: 80
      nodePort: 31853
