apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.postgres.deployment.pvc.claimName }}
  labels:
    app: {{ .Values.postgres.name }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
