apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.postgres.deployment.secret.name }}
  labels:
    app: {{ .Values.postgres.name }}
type: Opaque
data:
  {{ .Values.postgres.deployment.secret.userKey }}: {{ .Values.postgres.deployment.secret.userBase64 | quote }}
  {{ .Values.postgres.deployment.secret.passwordKey }}: {{ .Values.postgres.deployment.secret.passwordBase64 | quote }}
